<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYpqr8t7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYpqr8t7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYpqr8t7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYpqr8t7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYpqr8t7\appProdProjectContainer(array(
    'container.build_hash' => 'Ypqr8t7',
    'container.build_id' => 'ff35c7b9',
    'container.build_time' => 1548408568,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYpqr8t7');
